Project to TZ11
Perminand/java-filmorate pull request #12
Opened 2024-05-01 12:34 UTC by Perminand

2024-05-02 09:46 UTC, TomattmanYandex requested changes
Привет, выглядит хорошо но по компонентам не очень
Важно хорошо разделять логику по слоям
1) слой хранилища, умеет только работать с хранилищем, сохранять объекты и получать их выборки, обычно классы на уровне хранилища не связаны между собой, каждое хранилище отвечает только за свой объект
2) слой сервиса, на нем вся логика, он может обращаться к нескольким классам хранилищ, объединять данные из них, ну и в принципе вся логика на этом уровне, обычно на выходе уже готовый обьект
3) слой контроллера, обрабатывает запросы, их параметры, все связанное на веб слое, обычно не имеют сильной логики, максимум валидация входных параметров,  обработка ответа, валидация, обработка ошибок (иногда преобразование в дто)

надо поправить логику в соответствии с таким стилем

2024-05-02 09:46 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/Controller.java
> +public interface Controller<T> {
не всегда имеет смысл добавлять такие интерфейсы, так как не все контроллеры будут иметь такие методы

2024-05-02 09:46 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/Controller.java
> +public interface Controller<T> {
но интересная реализация, позволяет удачно разбивать контроллеры по реализациям

2024-05-02 09:46 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController() {
не имеет смысла создавать все конструкторы  для этого класса
так как мы не будем создавать обьект этого класса вручную (разве что в тестах) следует оставить только реализацию конструктора со всеми параметрами

2024-05-02 09:46 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
хороший вариант реализации
сделать FilmService final  и повесить на класс RequiredArgsConstructor такой конструктор будет создан автоматически и это удобнее так как если добавишь еще сервисы не прийдется ничего переписывать

2024-05-02 09:46 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.findById(id)
лучше чтобы сервис возвращал объект, и эта логика была на уровне сервиса
хранилище возвращает optional , сервис делает эту обработку и кидает ошибку а контроллер только возвращает данные

2024-05-02 09:46 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (count == null) {
есть у @RequestParam опция отвечающая за дефолтное значнеие

2024-05-02 09:46 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController implements Controller<User> {
тут будут те же комментарии

2024-05-02 09:46 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/exception/NullFoundIdException.java
> +public class NullFoundIdException extends RuntimeException {
очень тяжелое для понимания имя
назови например EntityNotFoundException

2024-05-02 09:46 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +public class ErrorResponse {
это больше не модель а DTO моделями обычно называют классы которые представляют бизнес модель

2024-05-02 09:46 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final LocalDate dateMark;
зачем на уровне класса эта переменная

2024-05-02 09:46 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final LocalDate dateMark;
если хочешь чтобы она была из конфига, повесь на нее аннотацию @Value
если это просто константа то private final static

2024-05-02 09:46 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(@Value("${filmorate.date-mark}") LocalDate dateMark,
тут то же что и на уровне контроллера, с аннотацией @RequiredArgsConstructor

2024-05-02 09:46 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/IntService.java
> +public interface IntService<T> {
Тут то же что и на уровне контроллера

2024-05-02 09:46 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/Controller.java
> +public interface Controller<T> {
хотя все же не удачная, ибо например лайки не вписываются в эту реализацию  и друзья тоже
поэтому на уровне контроллера такого не делают

2024-05-02 09:46 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/Controller.java
> +public interface Controller<T> {
иногда конечно делают  интерфейсы для контроллеров, но не дженерики, а конкретно под каждый контроллер и только для документации

2024-05-02 09:46 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidateUser.java
> +public class ValidateUser {
не за чем делать дополнительный класс для такого
это логика сервиса пользователей
плюс валидировать можно аннотациями

2024-05-02 09:46 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/ValidateUser.java
> +public class ValidateUser {
да и имя на очень удачное, хотя бы UserValidator

2024-05-02 09:46 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/memory/DataStorage.java
> +public class DataStorage<T> {
Усложнение конечно но на уровне репозитория оно уместно

2024-05-02 09:46 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/memory/InMemoryFilmStorage.java
> +    public InMemoryFilmStorage() {
с конструктором то же что и с другими конструкторами

2024-05-02 09:46 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/memory/InMemoryFilmStorage.java
> +    UserStorage userStorage;
1) модификаторы доступа
2) обычно репозитории не ссылаются друг на друга, все это решается на уровне сервиса

2024-05-04 08:18 UTC, Perminand commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +public class ErrorResponse {
Ничего не придумал как поместить в adapter

2024-05-04 20:35 UTC, TomattmanYandex approved these changes
Привет, пара моментов есть, но их если хочешь можешь поправить к следующему спринту
Принято

2024-05-04 20:35 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/adapter/ErrorResponse.java
> +package ru.yandex.practicum.filmorate.adapter;
Странное имя пакета
Есть такой тип обьектов как DTO Data Transfer Object обычно их создают чтобы передавать данные между разными уровнями, кажется тут имя пакета dto подошло бы лучше

2024-05-04 20:35 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    @Autowired
ну тут можно было бы инжектить так же как и на уровне контроллера

2024-05-04 20:35 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final UserService userService;
у этого может быть проблема с циркулярными зависимостями, поэтому иногда предпочитают инжектить репозитории
а уже если там есть сложная логика то тогда сервисы, но тут как минимум пока что все норм

2024-05-05 00:14 UTC, merged