Project to TZ12
Perminand/java-filmorate pull request #15
Opened 2024-06-08 13:04 UTC by Perminand

2024-06-08 20:29 UTC, TomattmanYandex requested changes
Привет, оставил некоторые коменты, думаю они будут много где повторяться, по поводу дополнительных запросов в базу, необходимо использовать Join для того чтобы на одну поерацию было максимум три  запроса вне зависимости от количества запрашиваемых обьектов, т.е. запрос за одним фильмом максимум три запроса, и запрос за всеми фильмами, максимум три запроса

2024-06-08 20:29 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +public class FilmController implements IntefaceController<Film> {
обычно на контроллер такого не вешают, потому что к примеру у тебя сейчас есть два метода, которые тут вообще не нужны

такое иногда делают, но только для документации, но тогда под каждый отдельный контроллер есть класс интерфейс, в котором очень много документирующих аннотаций

2024-06-08 20:29 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmStorage.java
> +package ru.yandex.practicum.filmorate.dal;
обычно этот пакет называют repository или dao

2024-06-08 20:29 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dal/db/storage/FilmDbStorage.java
> +    PreparedStatement stmt = null;
модификатор доступа

2024-06-08 20:29 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dal/db/storage/FilmDbStorage.java
> +        return jdbcTemplate.query("SELECT * FROM films", mapper);
вернутся без жанров рейтингов и всего остального

2024-06-08 20:29 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dal/db/storage/FilmDbStorage.java
> +        String query = "SELECT * FROM films WHERE film_id = ?";
и тут тоже вернется без всего

2024-06-08 20:29 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/dal/db/storage/GenreDbStorage.java
> +    PreparedStatement stmt = null;
везде  нужен будет модификатор

2024-06-09 04:18 UTC, Perminand commented on src/main/java/ru/yandex/practicum/filmorate/dal/db/storage/FilmDbStorage.java
> +        return jdbcTemplate.query("SELECT * FROM films", mapper);
Реализовал в сервисе

2024-06-09 04:19 UTC, Perminand commented on src/main/java/ru/yandex/practicum/filmorate/dal/db/storage/FilmDbStorage.java
> +        String query = "SELECT * FROM films WHERE film_id = ?";
Реализовано в сервисе

2024-06-09 14:23 UTC, TomattmanYandex requested changes
езе есть моменты на исправление

2024-06-09 14:23 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public void delete() {
эти методы тоже стоило бы удалить

2024-06-09 14:23 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.getAll()
я делал специально акцент на этом при прошлой проверке
Если будет сделан запрос за 100 фильмов
то сейчас будет сделан один запрос за всеми фильмами, вместе с их mpa а потом будет сделано еще 100 запросов за жанрами каждого из них
а необходимо чтобы вне зависимости от количества фильмов было 2 запроса

Подсказка как это решить, 
можно сделать запрос с условием wher film_id IN (список) 
после чего у тебя вернутся строки film_id, genre_id, genre_name
проходишь по всем строкам, и по film_id каждому фильму добавляем тот или иной жанр

2024-06-10 16:35 UTC, closed without merging

2024-06-10 21:44 UTC, TomattmanYandex reviewed
Принято